### ISSUE TITLE
Embed plunkers are broken

### ISSUE THREAD

**Issue by erwanv** [filearts/plunker_embed#2]
All < and >  are replaced by \&lt; and \&gt; in the HTML of every embed plunker. It breaks everything.

You can see examples in the embed plunkers on the official documentation here:
https://ggoodman.gitbooks.io/plunker/content/embed.html

Thanks!

**Comment by magnumjs** [comment]
I created similar issue in a different repo by mistake:  see https://github.com/filearts/plunker/issues/139

I noticed this yesterday

**Comment by erwanv** [comment]
The HTML problem has been fix but another issue seems to be remaining, see:
https://github.com/filearts/plunker/issues/140

Thank you for your awesome work!

**Comment by ggoodman** [comment]
Fixed earlier today. Thanks for reporting!
